'use client'

import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function Footer() {
  return (
    <footer className={`bg-white border-t border-gray-200 py-3 px-4 ${roboto.className}`}>
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-2">
        {/* Left Side - Company Info */}
        <div className="text-[11px] text-gray-500 text-center md:text-left">
          <span className="font-semibold text-[#0071BD] tracking-widest">HRMS</span>
          <span className="mx-1.5 text-gray-300 tracking-widest">|</span>
          <span className="tracking-widest">A to Zee Switchgear Engineering (SMC) Pvt. Ltd.</span>
        </div>

        {/* Right Side - Developer Credit */}
        <div className="text-[11px] text-gray-500 text-center md:text-right">
          <span className="tracking-widest">System and Software generated by </span>
          <span className="font-semibold text-[#0071BD] tracking-widest">Muhammad Hassan Jaffer</span>
        </div>
      </div>
    </footer>
  )
}